#!/usr/bin/env bash
# Usage: bin/build [python]
#
# Build or rebuild the installation (virtualenv, pip packages, Odoo modules).
# When building for the first time, optionally pass a different Python version
# (e.g. `bin/build python3.5`).

set -e
cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")"
source versions

if ! test -d env; then
    virtualenv --python "${1:-$PYTHON_VERSION}" env
elif test $# != 0; then
    echo "Warning: virtualenv already built, ignoring Python version"
fi

env/bin/pip install --upgrade \
            'git+https://github.com/janverb/git-aggregator@therp-patches#egg=git-aggregator' \
            'git+https://github.com/anybox/anybox.recipe.odoo#egg=anybox.recipe.odoo'


env/bin/gitaggregate --expand-env --env-file=versions --config=repos.yml --jobs=4 aggregate

env/bin/pip install -r <(
    bin/combine_requirements parts/odoo/requirements.txt requirements.txt
)
env/bin/pip install -e parts/odoo

bin/generate_config
