#!/usr/bin/env python3
"""Merge multiple requirements.txt files so that they can override each other.

Merges the files given as arguments and writes the result to stdout.

Mentioning a dependency in a file will ignore all mention of it in earlier
files.
"""

from collections import defaultdict
from sys import argv

from pkg_resources import Requirement


def read(fname):
    mapping = defaultdict(list)
    with open(fname) as f:
        for line in f:
            line = line.strip()
            if line.startswith("#") or not line:
                continue
            try:
                req = Requirement.parse(line)
                # Note that keys may not be unique
                mapping[req.key].append(str(req))
            except ValueError:
                # pkg_resources does not understand git+...
                # In such cases we just pass them through
                mapping[line].append(line)
    return mapping


def main(fnames):
    reqs = {}
    for fname in fnames:
        reqs.update(read(fname))
    for key in sorted(reqs):
        for req in reqs[key]:
            print(req)


if __name__ == "__main__":
    main(argv[1:])
