#!/usr/bin/env bash
basedir="$(dirname "$(dirname "${BASH_SOURCE[0]}")")"
python="$basedir"/env/bin/python
cfg="$basedir"/etc/odoo.cfg
if test -f "$basedir"/parts/odoo/odoo-bin; then
    odoo="$basedir"/parts/odoo/odoo-bin
else
    odoo="$basedir"/parts/odoo/odoo.py
fi

if ! test -f "$python" || ! test -f "$odoo"; then
    echo "Installation not built yet! Run bin/build"
    exit 1
fi

# If we're running a subcommand that has to be the first argument, prepending
# a -c option will break it. So check whether the first argument looks like
# an option.
case $1 in
    -* | '')
        exec "$python" "$odoo" -c "$cfg" "$@"
        ;;
    *)
        first=$1
        shift
        exec "$python" "$odoo" "$first" -c "$cfg" "$@"
        ;;
esac
