#!/usr/bin/env bash
# Wrapper around the original python_odoo for compatibility
# Consider using `odoo shell` instead

basedir="$(dirname "$(dirname "${BASH_SOURCE[0]}")")"
export basedir="$basedir"

setup='
import os, sys
from anybox.recipe.odoo.runtime.session import Session
basedir = os.environ["basedir"]
session = Session(os.path.join(basedir, "etc/odoo.cfg"), basedir)
'

if test $# = 0; then
    exec "$basedir"/env/bin/python -i -c "$setup"
elif test "$1" = "-c"; then
    shift
    command=$1
    shift
else
    command='
del sys.argv[0]
with open(sys.argv[0]) as _f:
    _script = _f.read()
exec(_script)
'
fi

exec "$basedir"/env/bin/python -c "$setup$command" "$@"
